version: '3.3'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5
    environment:
      - MYSQL_DATABASE=expenses_api
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345678
      - MYSQL_PORT=3306
    ports:
      - 33061:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_PASSWORD=12345678
      - PMA_HOST=mysql
    ports:
      - 8080:80
